### ISSUE TITLE
Enhance the Health-Check Functionality 

### ISSUE THREAD

**Issue by rohitthakur2590** [redhat-cop/network.base#15]
- Modiffy Default approach to Fail entire Health Check if any of the health check is unsuccessful
- Add `ignore_failure`  optin to all healh-checks
```yaml
---
- hosts: ios
  gather_facts: false
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.bgp.run
      vars:
        actions:
          - name: health_check
            vars:
              details: true
              checks:
                - name: all_neighbors_up
                  ignore_failure: true
                - name: all_neighbors_down
                  ignore_failure: true
                - name: min_neighbors_up
                  min_count: 1
```
