### ISSUE TITLE
Support Github SCM operations `retrieve` and `publish`with Persist and Deploy Actions

### ISSUE THREAD

**Issue by rohitthakur2590** [redhat-cop/network.base#38]
Support Github SCM operations with in Persist and Deploy Actions
##### SUMMARY

- Enable resource manager to fetch facts and save the host_vars to github repositories. 
- Enable resource manager to retrieve host_vars from github repository and deploy changes.

##### ISSUE TYPE
- Feature Idea

###### Default data store persist operation
```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        action: persist
        ansible_network_os: cisco.ios.ios
        resources:
          - 'interfaces'
          - 'l2_interfaces'
          - 'l3_interfaces'
          - 'bgp_global'
          - 'bgp_address_family'
          - 'ospf'
```

###### SCM  driven Operation
```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        action: persist
        ansible_network_os: cisco.ios.ios
        resources:
          - 'interfaces'
          - 'l2_interfaces'
          - 'l3_interfaces'
          - 'bgp_global'
          - 'bgp_address_family'
          - 'ospf'
        data_store:  
            scm:
              origin:
                 url: https://github.com/rohitthakur2590/network_validated_content_automation.git
                 token:  "{{ GH_PAT }}"
                 user:
                    name: rohitthakur2590
                    email: rohitthakur2590@outlook.com
```
###### Local data store driven persist operation
```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        action: persist
        ansible_network_os: cisco.ios.ios
        resources:
          - 'interfaces'
          - 'l2_interfaces'
          - 'l3_interfaces'
          - 'bgp_global'
          - 'bgp_address_family'
          - 'ospf'
        data_store:
          local: "~/backup/network"
```
###### SCM driven deploy operation
```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        action: deploy
        ansible_network_os: cisco.ios.ios
        resources:
          - 'all'
        data_store:  
          scm:
              origin:
                  url: https://github.com/rohitthakur2590/network_validated_content_automation.git
```

**Comment by NilashishC** [comment]
```yaml
scm:
  repo(or url):  git@github.com:rohitthakur2590/network_validated_content_automation.git
  token: superSecretToken
```

I would suggest something like this^ instead of `origin`, so that we support private repositories too, which would be the case for all production deployments. And then update the actual tasks to something like this - https://gist.github.com/NilashishC/a6a08fe16a24a5dd9b1b573aae62f413#file-eda-L14-L20

Suggestion for better names for the new keys are welcome.
