### ISSUE TITLE
check-drift task in detect operation doesn't work when resources are not defined

### ISSUE THREAD

**Issue by rohitthakur2590** [redhat-cop/network.base#43]
##### SUMMARY

check-drift task in detect operation doesn't work when resources are not defined

This doesn;t get caught because other than network.base we pass predefined set of resources within
network validated content collections.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

network.base

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = /home/rothakur/ansible-collections/collections/ansible_collections/network/base/ansible.cfg
  configured module search path = ['/home/rothakur/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/rothakur/ansible-collections/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = False
```

##### COLLECTION VERSION

```paste below
2.0.0
```

##### CONFIGURATION

```paste below
[defaults]
INVENTORY=./inventory
host_key_checking = False
collections_paths=/home/rothakur/ansible-collections/collections

[persistent_connection]
command_timeout = 100
connect_timeout = 100
connect_retry_timeout = 100
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: rtr1
  gather_facts: true
  tasks:
    - name: Network Resource Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        action: detect
        ansible_network_os: cisco.ios.ios
          scm:  
            origin:
              url: https://github.com/rohitthakur2590/network_validated_content_automation.git
              token: " {{ GH_PAT }}"
              user:
                name: rohitthakur2590
                email: rohitthakur2590@outlook.com

```

##### EXPECTED RESULTS

redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
fatal: [rtr1]: FAILED! => {
    "changed": false,
    "msg": "configuration drift is found in cisco.ios.ios_interfaces Resource"
}

##### ACTUAL RESULTS

```paste below
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
ok: [rtr1] => {
    "msg": "There is no configuration drift found"
}
```
