### ISSUE TITLE
To_nice_yaml reorders saved yaml at persist.

### ISSUE THREAD

**Issue by Roiki11** [redhat-cop/network.base#53]
##### SUMMARY

To_nice_yaml filter in persist task reorders the keys by default. This makes the output more difficult to read and different from what ansible shows with gather action.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

https://github.com/redhat-cop/network.base/blob/9e0265285c21374a2094d56b832e59aa47883359/roles/resource_manager/includes/write_to_file.yaml#L10

##### STEPS TO REPRODUCE

Without ```sort_keys=false ``` the output gets messed from the expected output shown with gather. Adding it produces expected output when compared to the output displayed by gather function. Examples below.

##### EXPECTED RESULTS

``` yaml

interfaces:
  - name: AppGigabitEthernet1/0/1
    enabled: false
  - name: FortyGigabitEtherneti/1/1
    enabled: false
  - name: FortyGigabitEthernet1/1/2
    enabled: false
  - name: GigabitEthernet0/0
    description: Management interface
    enabled: true

```

##### ACTUAL RESULTS

```yaml

interfaces:
 - enabled: false
   name: AppGigabitEthernet1/0/1
 - enabled: false
   name: FortyGigabitEthernet1/1/1
 - enabled: false
   name: FortyGigabitEthernet1/1/2
 - description: Management interface
   enabled: true
   name: GigabitEthernet0/0

```
